name: 'Terraform EKS Deploy and Destroy'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Actions'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan -out=tfplan

      - name: 'Terraform Apply'
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: 'Terraform Destroy'
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
